namespace SummerCampManagementSystem.BLL.DTOs.AI
{
    /// <summary>
    /// Response DTO for face recognition operation
    /// </summary>
    public class RecognitionResponse
    {
        /// <summary>
        /// Whether the recognition was successful
        /// </summary>
        public bool Success { get; set; }

        /// <summary>
        /// Status message from the Python AI service
        /// </summary>
        public string Message { get; set; } = string.Empty;

        /// <summary>
        /// The activity schedule ID for this recognition session
        /// </summary>
        public int ActivityScheduleId { get; set; }

        /// <summary>
        /// Session ID generated by the Python AI service
        /// </summary>
        public string SessionId { get; set; } = string.Empty;

        /// <summary>
        /// List of recognized campers
        /// </summary>
        public List<RecognizedCamper> RecognizedCampers { get; set; } = new();

        /// <summary>
        /// Total number of faces detected in the photo
        /// </summary>
        public int TotalFacesDetected { get; set; }

        /// <summary>
        /// Number of faces successfully matched
        /// </summary>
        public int MatchedFaces { get; set; }

        /// <summary>
        /// Processing time in milliseconds
        /// </summary>
        public long ProcessingTimeMs { get; set; }

        /// <summary>
        /// Timestamp of the recognition
        /// </summary>
        public DateTime Timestamp { get; set; }
    }
}
