// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Accommodation")]
[Index("accommodationTypeId", Name = "IX_Accommodation_accommodationTypeId")]
[Index("campId", Name = "IX_Accommodation_campId")]
public partial class Accommodation
{
    [Key]
    public int accommodationId { get; set; }

    public int? campId { get; set; }

    public int? accommodationTypeId { get; set; }

    [StringLength(255)]
    public string name { get; set; }

    public int? capacity { get; set; }

    public bool? isActive { get; set; }

    [InverseProperty("accommodation")]
    public virtual ICollection<CamperAccommodation> CamperAccommodations { get; set; } = new List<CamperAccommodation>();

    [ForeignKey("accommodationTypeId")]
    [InverseProperty("Accommodations")]
    public virtual AccommodationType accommodationType { get; set; }

    [ForeignKey("campId")]
    [InverseProperty("Accommodations")]
    public virtual Camp camp { get; set; }
}