// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("AccommodationType", Schema = "dbo")]
public partial class AccommodationType
{
    [Key]
    public int accommodationTypeId { get; set; }

    [StringLength(255)]
    public string name { get; set; }

    public string description { get; set; }

    public bool? isActive { get; set; }

    [InverseProperty("accommodationType")]
    public virtual ICollection<Accommodation> Accommodations { get; set; } = new List<Accommodation>();
}