// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("AccommodationActivitySchedule", Schema = "dbo")]
public partial class AccommodationActivitySchedule
{
    [Key]
    public int accommodationActivityScheduleId { get; set; }

    public int? accommodationId { get; set; }

    public int? activityScheduleId { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    [ForeignKey("accommodationId")]
    [InverseProperty("AccommodationActivitySchedules")]
    public virtual Accommodation accommodation { get; set; }

    [ForeignKey("activityScheduleId")]
    [InverseProperty("AccommodationActivitySchedules")]
    public virtual ActivitySchedule activitySchedule { get; set; }
}