// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Accommodation")]
public partial class Accommodation
{
    [Key]
    public int accommodationId { get; set; }

    public int? campId { get; set; }

    public int? accommodationTypeId { get; set; }

    public int? camperGroupId { get; set; }

    [StringLength(255)]
    public string name { get; set; }

    public int? capacity { get; set; }

    public bool? isActive { get; set; }

    [ForeignKey("accommodationTypeId")]
    [InverseProperty("Accommodations")]
    public virtual AccommodationType accommodationType { get; set; }

    [ForeignKey("campId")]
    [InverseProperty("Accommodations")]
    public virtual Camp camp { get; set; }

    [ForeignKey("camperGroupId")]
    [InverseProperty("Accommodations")]
    public virtual CamperGroup camperGroup { get; set; }
}