// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("ActivitySchedule")]
public partial class ActivitySchedule
{
    [Key]
    public int activityScheduleId { get; set; }

    public int activityId { get; set; }

    public int? staffId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? startTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? endTime { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    public bool? isLivestream { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string roomId { get; set; }

    public int? maxCapacity { get; set; }
}