// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Activity")]
public partial class Activity
{
    [Key]
    public int activityId { get; set; }

    public int? campId { get; set; }

    public int? staffId { get; set; }

    [StringLength(255)]
    public string activityType { get; set; }

    [StringLength(255)]
    public string name { get; set; }

    public string description { get; set; }

    [StringLength(255)]
    public string location { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? startTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? endTime { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    public bool? isLivestream { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string roomId { get; set; }

    [InverseProperty("activity")]
    public virtual ICollection<AttendanceLog> AttendanceLogs { get; set; } = new List<AttendanceLog>();

    [InverseProperty("activity")]
    public virtual ICollection<CamperActivity> CamperActivities { get; set; } = new List<CamperActivity>();

    [InverseProperty("activity")]
    public virtual ICollection<GroupActivity> GroupActivities { get; set; } = new List<GroupActivity>();

    [InverseProperty("activity")]
    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    [ForeignKey("campId")]
    [InverseProperty("Activities")]
    public virtual Camp camp { get; set; }

    [ForeignKey("staffId")]
    [InverseProperty("Activities")]
    public virtual UserAccount staff { get; set; }
}