// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Activity")]
public partial class Activity
{
    [Key]
    public int activityId { get; set; }

    [StringLength(255)]
    public string activityType { get; set; }

    [StringLength(255)]
    public string name { get; set; }

    public string description { get; set; }

    public int? campId { get; set; }

    [InverseProperty("activity")]
    public virtual ICollection<ActivitySchedule> ActivitySchedules { get; set; } = new List<ActivitySchedule>();

    [ForeignKey("campId")]
    [InverseProperty("Activities")]
    public virtual Camp camp { get; set; }
}