// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("ActivitySchedule")]
public partial class ActivitySchedule
{
    [Key]
    public int activityScheduleId { get; set; }

    public int activityId { get; set; }

    public int? staffId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? startTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? endTime { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    public bool? isLivestream { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string roomId { get; set; }

    public int? maxCapacity { get; set; }

    public bool isOptional { get; set; }

    public int? locationId { get; set; }

    public int? currentCapacity { get; set; }

    [InverseProperty("activitySchedule")]
    public virtual ICollection<AttendanceLog> AttendanceLogs { get; set; } = new List<AttendanceLog>();

    [InverseProperty("activitySchedule")]
    public virtual ICollection<CamperActivity> CamperActivities { get; set; } = new List<CamperActivity>();

    [InverseProperty("activitySchedule")]
    public virtual ICollection<GroupActivity> GroupActivities { get; set; } = new List<GroupActivity>();

    [InverseProperty("activitySchedule")]
    public virtual ICollection<RegistrationOptionalActivity> RegistrationOptionalActivities { get; set; } = new List<RegistrationOptionalActivity>();

    [ForeignKey("activityId")]
    [InverseProperty("ActivitySchedules")]
    public virtual Activity activity { get; set; }

    [ForeignKey("locationId")]
    [InverseProperty("ActivitySchedules")]
    public virtual Location location { get; set; }

    [ForeignKey("staffId")]
    [InverseProperty("ActivitySchedules")]
    public virtual UserAccount staff { get; set; }
}