// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Album")]
public partial class Album
{
    [Key]
    public int albumId { get; set; }

    public int? campId { get; set; }

    public DateOnly? date { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string title { get; set; }

    [Column(TypeName = "text")]
    public string description { get; set; }

    [InverseProperty("album")]
    public virtual ICollection<AlbumPhoto> AlbumPhotos { get; set; } = new List<AlbumPhoto>();

    [ForeignKey("campId")]
    [InverseProperty("Albums")]
    public virtual Camp camp { get; set; }
}