// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("AlbumPhotoFace")]
public partial class AlbumPhotoFace
{
    [Key]
    public int albumPhotoFaceId { get; set; }

    public int albumPhotoId { get; set; }

    [Required]
    public byte[] faceTemplate { get; set; }

    [ForeignKey("albumPhotoId")]
    [InverseProperty("AlbumPhotoFaces")]
    public virtual AlbumPhoto albumPhoto { get; set; }
}