// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("AlbumPhoto")]
[Index("albumId", Name = "IX_AlbumPhoto_albumId")]
public partial class AlbumPhoto
{
    [Key]
    public int albumPhotoId { get; set; }

    public int? albumId { get; set; }

    [StringLength(255)]
    public string photo { get; set; }

    [StringLength(255)]
    public string caption { get; set; }

    [InverseProperty("albumPhoto")]
    public virtual ICollection<AlbumPhotoFace> AlbumPhotoFaces { get; set; } = new List<AlbumPhotoFace>();

    [ForeignKey("albumId")]
    [InverseProperty("AlbumPhotos")]
    public virtual Album album { get; set; }
}