// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("AttendanceLog", Schema = "dbo")]
[Index("camperId", Name = "IX_AttendanceLog_camperId")]
[Index("staffId", Name = "IX_AttendanceLog_staffId")]
public partial class AttendanceLog
{
    [Key]
    public int attendanceLogId { get; set; }

    public int camperId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime timestamp { get; set; }

    [Required]
    [StringLength(50)]
    public string eventType { get; set; }

    [Required]
    [StringLength(50)]
    public string checkInMethod { get; set; }

    public int? staffId { get; set; }

    [StringLength(255)]
    public string note { get; set; }

    public int? activityScheduleId { get; set; }

    [StringLength(50)]
    public string participantStatus { get; set; }

    [ForeignKey("activityScheduleId")]
    [InverseProperty("AttendanceLogs")]
    public virtual ActivitySchedule activitySchedule { get; set; }

    [ForeignKey("camperId")]
    [InverseProperty("AttendanceLogs")]
    public virtual Camper camper { get; set; }

    [ForeignKey("staffId")]
    [InverseProperty("AttendanceLogs")]
    public virtual UserAccount staff { get; set; }
}