// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Badge")]
public partial class Badge
{
    [Key]
    public int badgeId { get; set; }

    [StringLength(255)]
    public string badgeName { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    [InverseProperty("badge")]
    public virtual ICollection<CampBadge> CampBadges { get; set; } = new List<CampBadge>();

    [InverseProperty("badge")]
    public virtual ICollection<CamperBadge> CamperBadges { get; set; } = new List<CamperBadge>();
}