// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("BankUser")]
[Index("userId", Name = "IX_BankUser_userId")]
public partial class BankUser
{
    [Key]
    public int bankUserId { get; set; }

    public int? userId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string bankCode { get; set; }

    [StringLength(255)]
    public string bankName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string bankNumber { get; set; }

    public bool? isPrimary { get; set; }

    public bool? isActive { get; set; }

    [ForeignKey("userId")]
    [InverseProperty("BankUsers")]
    public virtual UserAccount user { get; set; }
}