// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Blog", Schema = "dbo")]
[Index("authorId", Name = "IX_Blog_authorId")]
public partial class Blog
{
    [Key]
    public int blogId { get; set; }

    [StringLength(255)]
    public string title { get; set; }

    public string content { get; set; }

    public int? authorId { get; set; }

    public bool? isActive { get; set; }

    public string imageUrl { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createAt { get; set; }

    [ForeignKey("authorId")]
    [InverseProperty("Blogs")]
    public virtual UserAccount author { get; set; }
}