// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("CamperGuardian")]
[Index("camperId", Name = "IX_CamperGuardian_camperId")]
[Index("guardianId", Name = "IX_CamperGuardian_guardianId")]
public partial class CamperGuardian
{
    [Key]
    public int camperGuardianId { get; set; }

    public int? camperId { get; set; }

    public int? guardianId { get; set; }

    [ForeignKey("camperId")]
    [InverseProperty("CamperGuardians")]
    public virtual Camper camper { get; set; }

    [ForeignKey("guardianId")]
    [InverseProperty("CamperGuardians")]
    public virtual Guardian guardian { get; set; }
}