// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("CampType")]
public partial class CampType
{
    [Key]
    public int campTypeId { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string name { get; set; }

    [Column(TypeName = "text")]
    public string description { get; set; }

    public bool? isActive { get; set; }

    [InverseProperty("campType")]
    public virtual ICollection<Camp> Camps { get; set; } = new List<Camp>();
}