// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("CamperBadge")]
[Index("badgeId", Name = "IX_CamperBadge_badgeId")]
[Index("camperId", Name = "IX_CamperBadge_camperId")]
public partial class CamperBadge
{
    [Key]
    public int camperBadgeId { get; set; }

    public int? camperId { get; set; }

    public int? badgeId { get; set; }

    [ForeignKey("badgeId")]
    [InverseProperty("CamperBadges")]
    public virtual Badge badge { get; set; }

    [ForeignKey("camperId")]
    [InverseProperty("CamperBadges")]
    public virtual Camper camper { get; set; }
}