// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("CamperAccommodation")]
[Index("accommodationId", Name = "IX_CamperAccommodation_accommodationId")]
[Index("camperId", Name = "IX_CamperAccommodation_camperId")]
public partial class CamperAccommodation
{
    [Key]
    public int camperAccommodationId { get; set; }

    public int camperId { get; set; }

    public int accommodationId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? assignedAt { get; set; }

    [ForeignKey("accommodationId")]
    [InverseProperty("CamperAccommodations")]
    public virtual Accommodation accommodation { get; set; }

    [ForeignKey("camperId")]
    [InverseProperty("CamperAccommodations")]
    public virtual Camper camper { get; set; }
}