// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Camper")]
public partial class Camper
{
    [Key]
    public int camperId { get; set; }

    [StringLength(255)]
    public string camperName { get; set; }

    [StringLength(50)]
    public string gender { get; set; }

    public int? groupId { get; set; }

    public DateOnly? dob { get; set; }

    public byte[] faceTemplate { get; set; }

    public string avatar { get; set; }

    [InverseProperty("camper")]
    public virtual ICollection<AttendanceLog> AttendanceLogs { get; set; } = new List<AttendanceLog>();

    [InverseProperty("camper")]
    public virtual ICollection<CamperAccommodation> CamperAccommodations { get; set; } = new List<CamperAccommodation>();

    [InverseProperty("camper")]
    public virtual ICollection<CamperActivity> CamperActivities { get; set; } = new List<CamperActivity>();

    [InverseProperty("camper")]
    public virtual ICollection<CamperBadge> CamperBadges { get; set; } = new List<CamperBadge>();

    [InverseProperty("camper")]
    public virtual ICollection<CamperGuardian> CamperGuardians { get; set; } = new List<CamperGuardian>();

    [InverseProperty("camper")]
    public virtual HealthRecord HealthRecord { get; set; }

    [InverseProperty("camper")]
    public virtual ICollection<Incident> Incidents { get; set; } = new List<Incident>();

    [InverseProperty("camper")]
    public virtual ICollection<ParentCamper> ParentCampers { get; set; } = new List<ParentCamper>();

    [InverseProperty("camper")]
    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    [InverseProperty("camper")]
    public virtual ICollection<Visitation> Visitations { get; set; } = new List<Visitation>();

    [ForeignKey("groupId")]
    [InverseProperty("Campers")]
    public virtual CamperGroup group { get; set; }

    [ForeignKey("camperId")]
    [InverseProperty("campers")]
    public virtual ICollection<Registration> registrations { get; set; } = new List<Registration>();
}