// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Camper")]
public partial class Camper
{
    [Key]
    public int camperId { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string camperName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string gender { get; set; }

    public int? groupId { get; set; }

    public DateOnly? dob { get; set; }

    [InverseProperty("camper")]
    public virtual ICollection<CamperActivity> CamperActivities { get; set; } = new List<CamperActivity>();

    [InverseProperty("camper")]
    public virtual ICollection<CamperBadge> CamperBadges { get; set; } = new List<CamperBadge>();

    [InverseProperty("camper")]
    public virtual ICollection<CamperGuardian> CamperGuardians { get; set; } = new List<CamperGuardian>();

    [InverseProperty("camper")]
    public virtual ICollection<HealthRecord> HealthRecords { get; set; } = new List<HealthRecord>();

    [InverseProperty("camper")]
    public virtual ICollection<Incident> Incidents { get; set; } = new List<Incident>();

    [InverseProperty("camper")]
    public virtual ICollection<ParentCamper> ParentCampers { get; set; } = new List<ParentCamper>();

    [InverseProperty("camper")]
    public virtual ICollection<Registration> Registrations { get; set; } = new List<Registration>();

    [InverseProperty("camper")]
    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    [InverseProperty("camper")]
    public virtual ICollection<Visitation> Visitations { get; set; } = new List<Visitation>();

    [ForeignKey("groupId")]
    [InverseProperty("Campers")]
    public virtual CamperGroup group { get; set; }
}