// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("CamperActivity")]
[Index("activityScheduleId", Name = "IX_CamperActivity_activityScheduleId")]
[Index("camperId", Name = "IX_CamperActivity_camperId")]
public partial class CamperActivity
{
    [Key]
    public int camperActivityId { get; set; }

    public int? camperId { get; set; }

    public int? activityScheduleId { get; set; }

    [StringLength(50)]
    public string participationStatus { get; set; }

    [ForeignKey("activityScheduleId")]
    [InverseProperty("CamperActivities")]
    public virtual ActivitySchedule activitySchedule { get; set; }

    [ForeignKey("camperId")]
    [InverseProperty("CamperActivities")]
    public virtual Camper camper { get; set; }
}