// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("CampBadge")]
[Index("badgeId", Name = "IX_CampBadge_badgeId")]
[Index("campId", Name = "IX_CampBadge_campId")]
public partial class CampBadge
{
    [Key]
    public int campBadgeId { get; set; }

    public int? badgeId { get; set; }

    public int? campId { get; set; }

    [ForeignKey("badgeId")]
    [InverseProperty("CampBadges")]
    public virtual Badge badge { get; set; }

    [ForeignKey("campId")]
    [InverseProperty("CampBadges")]
    public virtual Camp camp { get; set; }
}