// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("CamperGroup", Schema = "dbo")]
public partial class CamperGroup
{
    [Key]
    public int camperGroupId { get; set; }

    public int camperId { get; set; }

    public int groupId { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    [ForeignKey("camperId")]
    [InverseProperty("CamperGroups")]
    public virtual Camper camper { get; set; }

    [ForeignKey("groupId")]
    [InverseProperty("CamperGroups")]
    public virtual Group group { get; set; }
}