// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("CamperTransport", Schema = "dbo")]
public partial class CamperTransport
{
    [Key]
    public int camperTransportId { get; set; }

    public int transportScheduleId { get; set; }

    public int camperId { get; set; }

    public int stopLocationId { get; set; }

    public bool? isAbsent { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? checkInTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? checkOutTime { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    [StringLength(255)]
    public string note { get; set; }

    [ForeignKey("camperId")]
    [InverseProperty("CamperTransports")]
    public virtual Camper camper { get; set; }

    [ForeignKey("stopLocationId")]
    [InverseProperty("CamperTransports")]
    public virtual Location stopLocation { get; set; }

    [ForeignKey("transportScheduleId")]
    [InverseProperty("CamperTransports")]
    public virtual TransportSchedule transportSchedule { get; set; }
}