// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("CamperActivity")]
public partial class CamperActivity
{
    [Key]
    public int camperActivityId { get; set; }

    public int? camperId { get; set; }

    public int? activityId { get; set; }

    [StringLength(50)]
    public string participationStatus { get; set; }

    [ForeignKey("activityId")]
    [InverseProperty("CamperActivities")]
    public virtual Activity activity { get; set; }

    [ForeignKey("camperId")]
    [InverseProperty("CamperActivities")]
    public virtual Camper camper { get; set; }
}