// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("CampStaffAssignment", Schema = "dbo")]
[Index("campId", Name = "IX_CampStaffAssignment_campId")]
[Index("staffId", Name = "IX_CampStaffAssignment_staffId")]
public partial class CampStaffAssignment
{
    [Key]
    public int campStaffAssignmentId { get; set; }

    public int? staffId { get; set; }

    public int? campId { get; set; }

    [ForeignKey("campId")]
    [InverseProperty("CampStaffAssignments")]
    public virtual Camp camp { get; set; }

    [ForeignKey("staffId")]
    [InverseProperty("CampStaffAssignments")]
    public virtual UserAccount staff { get; set; }
}