// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("ChatMessageAI")]
[Index("senderId", Name = "IX_ChatMessageAI_senderId")]
public partial class ChatMessageAI
{
    [Key]
    public int chatMessageAiId { get; set; }

    public int? senderId { get; set; }

    public string message { get; set; }

    public string response { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? messageCreateAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? responseAt { get; set; }

    [ForeignKey("senderId")]
    [InverseProperty("ChatMessageAIs")]
    public virtual UserAccount sender { get; set; }
}