// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("ChatConversation", Schema = "dbo")]
[Index("userId", Name = "IX_ChatMessageAI_senderId")]
public partial class ChatConversation
{
    [Key]
    public int chatConversationId { get; set; }

    public int userId { get; set; }

    public string title { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createdAt { get; set; }

    [InverseProperty("conversation")]
    public virtual ICollection<ChatMessage> ChatMessages { get; set; } = new List<ChatMessage>();

    [ForeignKey("userId")]
    [InverseProperty("ChatConversations")]
    public virtual UserAccount user { get; set; }
}