// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("ChatMessage")]
public partial class ChatMessage
{
    [Key]
    public int chatMessageId { get; set; }

    public int conversationId { get; set; }

    [Required]
    [StringLength(10)]
    public string role { get; set; }

    public string content { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? sentAt { get; set; }

    [ForeignKey("conversationId")]
    [InverseProperty("ChatMessages")]
    public virtual ChatConversation conversation { get; set; }
}