// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("ChatRoomUser")]
public partial class ChatRoomUser
{
    [Key]
    public int chatRoomUserId { get; set; }

    public int? chatRoomId { get; set; }

    public int? userId { get; set; }

    [ForeignKey("chatRoomId")]
    [InverseProperty("ChatRoomUsers")]
    public virtual ChatRoom chatRoom { get; set; }

    [ForeignKey("userId")]
    [InverseProperty("ChatRoomUsers")]
    public virtual UserAccount user { get; set; }
}