// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("ChatRoom", Schema = "dbo")]
public partial class ChatRoom
{
    [Key]
    public int chatRoomId { get; set; }

    [StringLength(255)]
    public string name { get; set; }

    [InverseProperty("chatRoom")]
    public virtual ICollection<ChatRoomUser> ChatRoomUsers { get; set; } = new List<ChatRoomUser>();

    [InverseProperty("chatRoom")]
    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();
}