// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("DriverVehicle", Schema = "dbo")]
[Index("driverId", Name = "IX_DriverVehicle_driverId")]
[Index("vehicleId", Name = "IX_DriverVehicle_vehicleId")]
public partial class DriverVehicle
{
    [Key]
    public int driverVehicleId { get; set; }

    public int? driverId { get; set; }

    public int? vehicleId { get; set; }

    [ForeignKey("driverId")]
    [InverseProperty("DriverVehicles")]
    public virtual Driver driver { get; set; }

    [ForeignKey("vehicleId")]
    [InverseProperty("DriverVehicles")]
    public virtual Vehicle vehicle { get; set; }
}