// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Driver", Schema = "dbo")]
[Index("userId", Name = "IX_Driver_userId")]
public partial class Driver
{
    [Key]
    public int driverId { get; set; }

    public int? userId { get; set; }

    [StringLength(255)]
    public string licenseNumber { get; set; }

    public DateOnly? licenseExpiry { get; set; }

    [StringLength(255)]
    public string driverAddress { get; set; }

    public string licensePhoto { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    public string UploadToken { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? TokenExpiry { get; set; }

    public bool? IsTokenUsed { get; set; }

    [InverseProperty("driver")]
    public virtual ICollection<DriverVehicle> DriverVehicles { get; set; } = new List<DriverVehicle>();

    [InverseProperty("driver")]
    public virtual ICollection<TransportSchedule> TransportSchedules { get; set; } = new List<TransportSchedule>();

    [ForeignKey("userId")]
    [InverseProperty("Drivers")]
    public virtual UserAccount user { get; set; }
}