// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SummerCampManagementSystem.DAL.Models;

public partial class Driver
{
    public int driverId { get; set; }

    public int userId { get; set; }

    public string driverName { get; set; }

    public string driverPhoneNumber { get; set; }

    public string driverAddress { get; set; }

    public string driverLicense { get; set; }

    public DateOnly? dob { get; set; }

    public virtual ICollection<DriverVehicle> DriverVehicles { get; set; } = new List<DriverVehicle>();

    public virtual User user { get; set; }
}