// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SummerCampManagementSystem.DAL.Models;

public partial class DriverVehicle
{
    public int driverVehicleId { get; set; }

    public int driverId { get; set; }

    public int vehicleId { get; set; }

    public virtual Driver driver { get; set; }

    public virtual Vehicle vehicle { get; set; }
}