// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("DriverSchedule")]
[Index("campId", Name = "IX_DriverSchedule_campId")]
[Index("driverId", Name = "IX_DriverSchedule_driverId")]
[Index("vehicleId", Name = "IX_DriverSchedule_vehicleId")]
public partial class DriverSchedule
{
    [Key]
    public int driverScheduleId { get; set; }

    public int? driverId { get; set; }

    public int? vehicleId { get; set; }

    public int? campId { get; set; }

    public DateOnly? workDate { get; set; }

    public TimeOnly? startTime { get; set; }

    public TimeOnly? endTime { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    [ForeignKey("campId")]
    [InverseProperty("DriverSchedules")]
    public virtual Camp camp { get; set; }

    [ForeignKey("driverId")]
    [InverseProperty("DriverSchedules")]
    public virtual Driver driver { get; set; }

    [ForeignKey("vehicleId")]
    [InverseProperty("DriverSchedules")]
    public virtual Vehicle vehicle { get; set; }
}