// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("FAQ")]
public partial class FAQ
{
    [Key]
    public int faqId { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string question { get; set; }

    [Column(TypeName = "text")]
    public string answer { get; set; }
}