// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("FAQ", Schema = "dbo")]
public partial class FAQ
{
    [Key]
    public int faqId { get; set; }

    [StringLength(255)]
    public string question { get; set; }

    public string answer { get; set; }
}