// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Feedback", Schema = "dbo")]
[Index("registrationId", Name = "IX_Feedback_registrationId")]
public partial class Feedback
{
    [Key]
    public int feedbackId { get; set; }

    public int registrationId { get; set; }

    public int? rating { get; set; }

    public string comment { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? updateAt { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    public string rejectionReason { get; set; }

    public string managerReply { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? replyAt { get; set; }

    [ForeignKey("registrationId")]
    [InverseProperty("Feedbacks")]
    public virtual Registration registration { get; set; }
}