// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Feedback")]
public partial class Feedback
{
    [Key]
    public int feedbackId { get; set; }

    public int? registrationId { get; set; }

    public int? userId { get; set; }

    public int? rating { get; set; }

    public string comment { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createAt { get; set; }

    public int? campId { get; set; }

    [ForeignKey("campId")]
    [InverseProperty("Feedbacks")]
    public virtual Camp camp { get; set; }

    [ForeignKey("registrationId")]
    [InverseProperty("Feedbacks")]
    public virtual Registration registration { get; set; }

    [ForeignKey("userId")]
    [InverseProperty("Feedbacks")]
    public virtual UserAccount user { get; set; }
}