// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("GroupActivity")]
public partial class GroupActivity
{
    [Key]
    public int groupActivityId { get; set; }

    public int? camperGroupId { get; set; }

    public int? activityId { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    [ForeignKey("activityId")]
    [InverseProperty("GroupActivities")]
    public virtual Activity activity { get; set; }

    [ForeignKey("camperGroupId")]
    [InverseProperty("GroupActivities")]
    public virtual CamperGroup camperGroup { get; set; }
}