// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("GroupActivity", Schema = "dbo")]
[Index("activityScheduleId", Name = "IX_GroupActivity_activityId")]
[Index("groupId", Name = "IX_GroupActivity_camperGroupId")]
public partial class GroupActivity
{
    [Key]
    public int groupActivityId { get; set; }

    public int? groupId { get; set; }

    public int? activityScheduleId { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    [ForeignKey("activityScheduleId")]
    [InverseProperty("GroupActivities")]
    public virtual ActivitySchedule activitySchedule { get; set; }

    [ForeignKey("groupId")]
    [InverseProperty("GroupActivities")]
    public virtual Group group { get; set; }
}