// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Group", Schema = "dbo")]
[Index("campId", Name = "IX_CamperGroup_campId")]
[Index("supervisorId", Name = "IX_CamperGroup_supervisorId")]
public partial class Group
{
    [Key]
    public int groupId { get; set; }

    [StringLength(255)]
    public string groupName { get; set; }

    public string description { get; set; }

    public int? currentSize { get; set; }

    public int? maxSize { get; set; }

    public int? supervisorId { get; set; }

    public int? campId { get; set; }

    public int? minAge { get; set; }

    public int? maxAge { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    [InverseProperty("group")]
    public virtual ICollection<CamperGroup> CamperGroups { get; set; } = new List<CamperGroup>();

    [InverseProperty("group")]
    public virtual ICollection<GroupActivity> GroupActivities { get; set; } = new List<GroupActivity>();

    [ForeignKey("campId")]
    [InverseProperty("Groups")]
    public virtual Camp camp { get; set; }

    [ForeignKey("supervisorId")]
    [InverseProperty("Groups")]
    public virtual UserAccount supervisor { get; set; }
}