// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Guardian", Schema = "dbo")]
public partial class Guardian
{
    [Key]
    public int guardianId { get; set; }

    [StringLength(255)]
    public string fullName { get; set; }

    [StringLength(50)]
    public string title { get; set; }

    [StringLength(50)]
    public string gender { get; set; }

    public DateOnly? dob { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string email { get; set; }

    public bool? isActive { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string phoneNumber { get; set; }

    [InverseProperty("guardian")]
    public virtual ICollection<CamperGuardian> CamperGuardians { get; set; } = new List<CamperGuardian>();
}