// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("HealthRecord", Schema = "dbo")]
public partial class HealthRecord
{
    [Key]
    public int healthRecordId { get; set; }

    public string condition { get; set; }

    public string allergies { get; set; }

    public bool? isAllergy { get; set; }

    public string note { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createAt { get; set; }

    public int? camperId { get; set; }

    [ForeignKey("camperId")]
    [InverseProperty("HealthRecord")]
    public virtual Camper camper { get; set; }
}