// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Incident")]
public partial class Incident
{
    [Key]
    public int incidentId { get; set; }

    [Column(TypeName = "text")]
    public string description { get; set; }

    public DateOnly? incidentDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string status { get; set; }

    [Column(TypeName = "text")]
    public string note { get; set; }

    public int? camperId { get; set; }

    public int? campStaffId { get; set; }

    public int? campId { get; set; }

    [ForeignKey("campId")]
    [InverseProperty("Incidents")]
    public virtual Camp camp { get; set; }

    [ForeignKey("campStaffId")]
    [InverseProperty("Incidents")]
    public virtual UserAccount campStaff { get; set; }

    [ForeignKey("camperId")]
    [InverseProperty("Incidents")]
    public virtual Camper camper { get; set; }
}