// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("LivestreamUser")]
[Index("livestreamId", Name = "IX_LivestreamUser_livestreamId")]
[Index("userId", Name = "IX_LivestreamUser_userId")]
public partial class LivestreamUser
{
    [Key]
    public int livestreamUserId { get; set; }

    public int? livestreamId { get; set; }

    public int? userId { get; set; }

    [ForeignKey("livestreamId")]
    [InverseProperty("LivestreamUsers")]
    public virtual Livestream livestream { get; set; }

    [ForeignKey("userId")]
    [InverseProperty("LivestreamUsers")]
    public virtual UserAccount user { get; set; }
}