// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Livestream", Schema = "dbo")]
[Index("hostId", Name = "IX_Livestream_hostId")]
public partial class Livestream
{
    [Key]
    public int livestreamId { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string roomId { get; set; }

    [StringLength(255)]
    public string title { get; set; }

    public int? hostId { get; set; }

    [InverseProperty("livestream")]
    public virtual ICollection<ActivitySchedule> ActivitySchedules { get; set; } = new List<ActivitySchedule>();

    [ForeignKey("hostId")]
    [InverseProperty("Livestreams")]
    public virtual UserAccount host { get; set; }
}