// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Location")]
public partial class Location
{
    [Key]
    public int locationId { get; set; }

    public int? routeId { get; set; }

    [StringLength(255)]
    public string name { get; set; }

    [StringLength(50)]
    public string locationType { get; set; }

    public bool? isActive { get; set; }

    [InverseProperty("location")]
    public virtual ICollection<Activity> Activities { get; set; } = new List<Activity>();

    [InverseProperty("location")]
    public virtual ICollection<Camp> Camps { get; set; } = new List<Camp>();

    [ForeignKey("routeId")]
    [InverseProperty("Locations")]
    public virtual Route route { get; set; }
}