// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Location", Schema = "dbo")]
public partial class Location
{
    [Key]
    public int locationId { get; set; }

    [StringLength(255)]
    public string name { get; set; }

    [StringLength(50)]
    public string locationType { get; set; }

    public bool? isActive { get; set; }

    [StringLength(500)]
    public string address { get; set; }

    [Column(TypeName = "decimal(10, 8)")]
    public decimal? latitude { get; set; }

    [Column(TypeName = "decimal(11, 8)")]
    public decimal? longitude { get; set; }

    [InverseProperty("location")]
    public virtual ICollection<ActivitySchedule> ActivitySchedules { get; set; } = new List<ActivitySchedule>();

    [InverseProperty("location")]
    public virtual ICollection<Camp> Camps { get; set; } = new List<Camp>();

    [InverseProperty("location")]
    public virtual ICollection<RouteStop> RouteStops { get; set; } = new List<RouteStop>();
}