// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("ManagerAssignment")]
public partial class ManagerAssignment
{
    [Key]
    public int managerAssignmentId { get; set; }

    public int? managerId { get; set; }

    public int? campId { get; set; }

    [ForeignKey("campId")]
    [InverseProperty("ManagerAssignments")]
    public virtual Camp camp { get; set; }

    [ForeignKey("managerId")]
    [InverseProperty("ManagerAssignments")]
    public virtual UserAccount manager { get; set; }
}