// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Message")]
public partial class Message
{
    [Key]
    public int messageId { get; set; }

    public int? chatRoomId { get; set; }

    public int? senderId { get; set; }

    public string content { get; set; }

    public int? receiverId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createAt { get; set; }

    [ForeignKey("chatRoomId")]
    [InverseProperty("Messages")]
    public virtual ChatRoom chatRoom { get; set; }

    [ForeignKey("receiverId")]
    [InverseProperty("Messagereceivers")]
    public virtual UserAccount receiver { get; set; }

    [ForeignKey("senderId")]
    [InverseProperty("Messagesenders")]
    public virtual UserAccount sender { get; set; }
}