// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Notifications", Schema = "dbo")]
[Index("userId", Name = "IX_Notifications_userId")]
public partial class Notification
{
    [Key]
    public int notificationId { get; set; }

    [StringLength(255)]
    public string title { get; set; }

    public string message { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createAt { get; set; }

    public int? userId { get; set; }

    [ForeignKey("userId")]
    [InverseProperty("Notifications")]
    public virtual UserAccount user { get; set; }
}