// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("ParentCamper")]
[Index("camperId", Name = "IX_ParentCamper_camperId")]
[Index("parentId", Name = "IX_ParentCamper_parentId")]
public partial class ParentCamper
{
    [Key]
    public int parentCamperId { get; set; }

    public int? parentId { get; set; }

    public int? camperId { get; set; }

    [StringLength(255)]
    public string relationship { get; set; }

    [ForeignKey("camperId")]
    [InverseProperty("ParentCampers")]
    public virtual Camper camper { get; set; }

    [ForeignKey("parentId")]
    [InverseProperty("ParentCampers")]
    public virtual UserAccount parent { get; set; }
}