// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Payment")]
public partial class Payment
{
    [Key]
    public int paymentId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? amount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? paymentDate { get; set; }

    [StringLength(50)]
    public string method { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    [StringLength(255)]
    public string transactionCode { get; set; }

    public int? registrationId { get; set; }

    [ForeignKey("registrationId")]
    [InverseProperty("Payments")]
    public virtual Registration registration { get; set; }
}