// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("PromotionType")]
public partial class PromotionType
{
    [Key]
    public int promotionTypeId { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string name { get; set; }

    [Column(TypeName = "text")]
    public string description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? updateAt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string status { get; set; }

    [InverseProperty("promotionType")]
    public virtual ICollection<Promotion> Promotions { get; set; } = new List<Promotion>();
}