// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Promotion", Schema = "dbo")]
[Index("createBy", Name = "IX_Promotion_createBy")]
[Index("promotionTypeId", Name = "IX_Promotion_promotionTypeId")]
public partial class Promotion
{
    [Key]
    public int promotionId { get; set; }

    [StringLength(255)]
    public string name { get; set; }

    public string description { get; set; }

    public DateOnly? startDate { get; set; }

    public DateOnly? endDate { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? percent { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? maxDiscountAmount { get; set; }

    public int? createBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createAt { get; set; }

    public int? promotionTypeId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string code { get; set; }

    [InverseProperty("promotion")]
    public virtual ICollection<Camp> Camps { get; set; } = new List<Camp>();

    [InverseProperty("appliedPromotion")]
    public virtual ICollection<Registration> Registrations { get; set; } = new List<Registration>();

    [ForeignKey("createBy")]
    [InverseProperty("Promotions")]
    public virtual UserAccount createByNavigation { get; set; }

    [ForeignKey("promotionTypeId")]
    [InverseProperty("Promotions")]
    public virtual PromotionType promotionType { get; set; }
}