// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("RefreshToken")]
public partial class RefreshToken
{
    [Key]
    public int id { get; set; }

    public int userId { get; set; }

    [Required]
    [StringLength(255)]
    public string token { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime createdAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime expiresAt { get; set; }

    public bool isRevoked { get; set; }

    [ForeignKey("userId")]
    [InverseProperty("RefreshTokens")]
    public virtual UserAccount user { get; set; }
}