// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("RefundPolicy", Schema = "dbo")]
public partial class RefundPolicy
{
    [Key]
    public int refundPolictyId { get; set; }

    public int? campId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? daysBeforeStart { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? refundPercentage { get; set; }

    public string description { get; set; }

    public bool? isActive { get; set; }

    [ForeignKey("campId")]
    [InverseProperty("RefundPolicies")]
    public virtual Camp camp { get; set; }
}