// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Registration", Schema = "dbo")]
[Index("appliedPromotionId", Name = "IX_Registration_appliedPromotionId")]
[Index("campId", Name = "IX_Registration_campId")]
[Index("userId", Name = "IX_Registration_userId")]
public partial class Registration
{
    [Key]
    public int registrationId { get; set; }

    public int? campId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? registrationCreateAt { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    public int? appliedPromotionId { get; set; }

    public string note { get; set; }

    public int? userId { get; set; }

    public string rejectReason { get; set; }

    [InverseProperty("registration")]
    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    [InverseProperty("registration")]
    public virtual ICollection<RegistrationCamper> RegistrationCampers { get; set; } = new List<RegistrationCamper>();

    [InverseProperty("registration")]
    public virtual ICollection<RegistrationCancel> RegistrationCancels { get; set; } = new List<RegistrationCancel>();

    [InverseProperty("registration")]
    public virtual ICollection<RegistrationOptionalActivity> RegistrationOptionalActivities { get; set; } = new List<RegistrationOptionalActivity>();

    [InverseProperty("registration")]
    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    [ForeignKey("appliedPromotionId")]
    [InverseProperty("Registrations")]
    public virtual Promotion appliedPromotion { get; set; }

    [ForeignKey("campId")]
    [InverseProperty("Registrations")]
    public virtual Camp camp { get; set; }

    [ForeignKey("userId")]
    [InverseProperty("Registrations")]
    public virtual UserAccount user { get; set; }
}