// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("RegistrationCancel")]
[Index("registrationId", Name = "IX_RegistrationCancel_registrationId")]
public partial class RegistrationCancel
{
    [Key]
    public int registrationCancelId { get; set; }

    public int? registrationId { get; set; }

    public string reason { get; set; }

    [StringLength(255)]
    public string imageRefund { get; set; }

    [ForeignKey("registrationId")]
    [InverseProperty("RegistrationCancels")]
    public virtual Registration registration { get; set; }
}