// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("RegistrationCancel", Schema = "dbo")]
[Index("registrationId", Name = "IX_RegistrationCancel_registrationId")]
public partial class RegistrationCancel
{
    [Key]
    public int registrationCancelId { get; set; }

    public int? registrationId { get; set; }

    public int? bankUserId { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? refundAmount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? requestDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? approvalDate { get; set; }

    public string note { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    public string reason { get; set; }

    public string imageRefund { get; set; }

    [StringLength(255)]
    public string transactionCode { get; set; }

    [ForeignKey("bankUserId")]
    [InverseProperty("RegistrationCancels")]
    public virtual BankUser bankUser { get; set; }

    [ForeignKey("registrationId")]
    [InverseProperty("RegistrationCancels")]
    public virtual Registration registration { get; set; }
}