// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Registration")]
public partial class Registration
{
    [Key]
    public int registrationId { get; set; }

    public int? camperId { get; set; }

    public int? campId { get; set; }

    public int? paymentId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? registrationCreateAt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string status { get; set; }

    public int? appliedPromotionId { get; set; }

    [InverseProperty("registration")]
    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    [InverseProperty("registration")]
    public virtual ICollection<RegistrationCancel> RegistrationCancels { get; set; } = new List<RegistrationCancel>();

    [InverseProperty("registration")]
    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    [ForeignKey("appliedPromotionId")]
    [InverseProperty("Registrations")]
    public virtual Promotion appliedPromotion { get; set; }

    [ForeignKey("campId")]
    [InverseProperty("Registrations")]
    public virtual Camp camp { get; set; }

    [ForeignKey("camperId")]
    [InverseProperty("Registrations")]
    public virtual Camper camper { get; set; }

    [ForeignKey("paymentId")]
    [InverseProperty("Registrations")]
    public virtual Payment payment { get; set; }
}