// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("RegistrationOptionalActivity", Schema = "dbo")]
public partial class RegistrationOptionalActivity
{
    [Key]
    public int registrationOptionalActivityId { get; set; }

    public int registrationId { get; set; }

    public int camperId { get; set; }

    public int activityScheduleId { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createdTime { get; set; }

    [ForeignKey("activityScheduleId")]
    [InverseProperty("RegistrationOptionalActivities")]
    public virtual ActivitySchedule activitySchedule { get; set; }

    [ForeignKey("camperId")]
    [InverseProperty("RegistrationOptionalActivities")]
    public virtual Camper camper { get; set; }

    [ForeignKey("registrationId")]
    [InverseProperty("RegistrationOptionalActivities")]
    public virtual Registration registration { get; set; }
}