// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[PrimaryKey("registrationId", "camperId")]
[Table("RegistrationCamper", Schema = "dbo")]
[Index("camperId", Name = "IX_RegistrationCamper_camperId")]
public partial class RegistrationCamper
{
    [Key]
    public int registrationId { get; set; }

    [Key]
    public int camperId { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    public bool? requestTransport { get; set; }

    [ForeignKey("camperId")]
    [InverseProperty("RegistrationCampers")]
    public virtual Camper camper { get; set; }

    [ForeignKey("registrationId")]
    [InverseProperty("RegistrationCampers")]
    public virtual Registration registration { get; set; }
}