// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Report", Schema = "dbo")]
[Index("activityScheduleId", Name = "IX_Report_activityId")]
[Index("camperId", Name = "IX_Report_camperId")]
[Index("reportedBy", Name = "IX_Report_reportedBy")]
public partial class Report
{
    [Key]
    public int reportId { get; set; }

    public int? camperId { get; set; }

    public int? transportScheduleId { get; set; }

    [StringLength(50)]
    public string reportType { get; set; }

    public string note { get; set; }

    [StringLength(255)]
    public string image { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createAt { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    public int? reportedBy { get; set; }

    public int? activityScheduleId { get; set; }

    [StringLength(50)]
    public string level { get; set; }

    [ForeignKey("activityScheduleId")]
    [InverseProperty("Reports")]
    public virtual ActivitySchedule activitySchedule { get; set; }

    [ForeignKey("camperId")]
    [InverseProperty("Reports")]
    public virtual Camper camper { get; set; }

    [ForeignKey("reportedBy")]
    [InverseProperty("Reports")]
    public virtual UserAccount reportedByNavigation { get; set; }

    [ForeignKey("transportScheduleId")]
    [InverseProperty("Reports")]
    public virtual TransportSchedule transportSchedule { get; set; }
}