// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Report")]
public partial class Report
{
    [Key]
    public int reportId { get; set; }

    public int? camperId { get; set; }

    [Column(TypeName = "text")]
    public string note { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string image { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createAt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string status { get; set; }

    public int? reportedBy { get; set; }

    public int? activityId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string level { get; set; }

    [ForeignKey("activityId")]
    [InverseProperty("Reports")]
    public virtual Activity activity { get; set; }

    [ForeignKey("camperId")]
    [InverseProperty("Reports")]
    public virtual Camper camper { get; set; }

    [ForeignKey("reportedBy")]
    [InverseProperty("Reports")]
    public virtual UserAccount reportedByNavigation { get; set; }
}