// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Route", Schema = "dbo")]
[Index("campId", Name = "IX_Route_campId")]
public partial class Route
{
    [Key]
    public int routeId { get; set; }

    public int? campId { get; set; }

    [StringLength(255)]
    public string routeName { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    [StringLength(50)]
    public string routeType { get; set; }

    public int? estimateDuration { get; set; }

    public bool? isActive { get; set; }

    [InverseProperty("route")]
    public virtual ICollection<RouteStop> RouteStops { get; set; } = new List<RouteStop>();

    [InverseProperty("route")]
    public virtual ICollection<TransportSchedule> TransportSchedules { get; set; } = new List<TransportSchedule>();

    [ForeignKey("campId")]
    [InverseProperty("Routes")]
    public virtual Camp camp { get; set; }
}