// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Route")]
[Index("campId", Name = "IX_Route_campId")]
public partial class Route
{
    [Key]
    public int routeId { get; set; }

    public int? campId { get; set; }

    [StringLength(255)]
    public string routeName { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    [InverseProperty("route")]
    public virtual ICollection<Location> Locations { get; set; } = new List<Location>();

    [InverseProperty("route")]
    public virtual ICollection<VehicleSchedule> VehicleSchedules { get; set; } = new List<VehicleSchedule>();

    [ForeignKey("campId")]
    [InverseProperty("Routes")]
    public virtual Camp camp { get; set; }
}