// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("RouteStop")]
[Index("routeId", "locationId", Name = "UC_RouteStop_Location", IsUnique = true)]
[Index("routeId", "stopOrder", Name = "UC_RouteStop_Order", IsUnique = true)]
public partial class RouteStop
{
    [Key]
    public int routeStopId { get; set; }

    public int routeId { get; set; }

    public int locationId { get; set; }

    public int stopOrder { get; set; }

    public int? estimatedTime { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string status { get; set; }

    [ForeignKey("locationId")]
    [InverseProperty("RouteStops")]
    public virtual Location location { get; set; }

    [ForeignKey("routeId")]
    [InverseProperty("RouteStops")]
    public virtual Route route { get; set; }
}