// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("TransportStaffAssignment", Schema = "dbo")]
public partial class TransportStaffAssignment
{
    [Key]
    public int transportStaffAssignmentId { get; set; }

    public int? transportScheduleId { get; set; }

    public int? staffId { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    [ForeignKey("staffId")]
    [InverseProperty("TransportStaffAssignments")]
    public virtual UserAccount staff { get; set; }

    [ForeignKey("transportScheduleId")]
    [InverseProperty("TransportStaffAssignments")]
    public virtual TransportSchedule transportSchedule { get; set; }
}