// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("TransportSchedule", Schema = "dbo")]
public partial class TransportSchedule
{
    [Key]
    public int transportScheduleId { get; set; }

    public int? campId { get; set; }

    public int? vehicleId { get; set; }

    public int? driverId { get; set; }

    public int? routeId { get; set; }

    public DateOnly? date { get; set; }

    public TimeOnly? startTime { get; set; }

    public TimeOnly? endTime { get; set; }

    public TimeOnly? actualStartTime { get; set; }

    public TimeOnly? actualEndTime { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    public string cancelReasons { get; set; }

    public string transportType { get; set; }

    [InverseProperty("transportSchedule")]
    public virtual ICollection<CamperTransport> CamperTransports { get; set; } = new List<CamperTransport>();

    [InverseProperty("transportSchedule")]
    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    [InverseProperty("transportSchedule")]
    public virtual ICollection<TransportStaffAssignment> TransportStaffAssignments { get; set; } = new List<TransportStaffAssignment>();

    [ForeignKey("campId")]
    [InverseProperty("TransportSchedules")]
    public virtual Camp camp { get; set; }

    [ForeignKey("driverId")]
    [InverseProperty("TransportSchedules")]
    public virtual Driver driver { get; set; }

    [ForeignKey("routeId")]
    [InverseProperty("TransportSchedules")]
    public virtual Route route { get; set; }

    [ForeignKey("vehicleId")]
    [InverseProperty("TransportSchedules")]
    public virtual Vehicle vehicle { get; set; }
}