// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Transaction")]
[Index("registrationId", Name = "IX_Transaction_registrationId")]
public partial class Transaction
{
    [Key]
    public int transactionId { get; set; }

    public int? registrationId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? amount { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    [StringLength(50)]
    public string type { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? transactionTime { get; set; }

    [StringLength(50)]
    public string method { get; set; }

    [StringLength(255)]
    public string transactionCode { get; set; }

    [ForeignKey("registrationId")]
    [InverseProperty("Transactions")]
    public virtual Registration registration { get; set; }
}