// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("UserAccount", Schema = "dbo")]
public partial class UserAccount
{
    [Key]
    public int userId { get; set; }

    [StringLength(255)]
    public string firstName { get; set; }

    [StringLength(255)]
    public string lastName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string email { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string phoneNumber { get; set; }

    [StringLength(255)]
    public string password { get; set; }

    [StringLength(50)]
    public string role { get; set; }

    public bool? isActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createAt { get; set; }

    [StringLength(255)]
    public string avatar { get; set; }

    public DateOnly? dob { get; set; }

    [InverseProperty("staff")]
    public virtual ICollection<ActivitySchedule> ActivitySchedules { get; set; } = new List<ActivitySchedule>();

    [InverseProperty("staff")]
    public virtual ICollection<AttendanceLog> AttendanceLogs { get; set; } = new List<AttendanceLog>();

    [InverseProperty("user")]
    public virtual ICollection<BankUser> BankUsers { get; set; } = new List<BankUser>();

    [InverseProperty("author")]
    public virtual ICollection<Blog> Blogs { get; set; } = new List<Blog>();

    [InverseProperty("staff")]
    public virtual ICollection<CampStaffAssignment> CampStaffAssignments { get; set; } = new List<CampStaffAssignment>();

    [InverseProperty("supervisor")]
    public virtual ICollection<CamperGroup> CamperGroups { get; set; } = new List<CamperGroup>();

    [InverseProperty("createByNavigation")]
    public virtual ICollection<Camp> Camps { get; set; } = new List<Camp>();

    [InverseProperty("sender")]
    public virtual ICollection<ChatMessageAI> ChatMessageAIs { get; set; } = new List<ChatMessageAI>();

    [InverseProperty("user")]
    public virtual ICollection<ChatRoomUser> ChatRoomUsers { get; set; } = new List<ChatRoomUser>();

    [InverseProperty("user")]
    public virtual ICollection<Driver> Drivers { get; set; } = new List<Driver>();

    [InverseProperty("user")]
    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    [InverseProperty("host")]
    public virtual ICollection<Livestream> Livestreams { get; set; } = new List<Livestream>();

    [InverseProperty("receiver")]
    public virtual ICollection<Message> Messagereceivers { get; set; } = new List<Message>();

    [InverseProperty("sender")]
    public virtual ICollection<Message> Messagesenders { get; set; } = new List<Message>();

    [InverseProperty("user")]
    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    [InverseProperty("parent")]
    public virtual ICollection<ParentCamper> ParentCampers { get; set; } = new List<ParentCamper>();

    [InverseProperty("createByNavigation")]
    public virtual ICollection<Promotion> Promotions { get; set; } = new List<Promotion>();

    [InverseProperty("user")]
    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    [InverseProperty("user")]
    public virtual ICollection<Registration> Registrations { get; set; } = new List<Registration>();

    [InverseProperty("reportedByNavigation")]
    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    [InverseProperty("approvedByNavigation")]
    public virtual ICollection<Visitation> VisitationapprovedByNavigations { get; set; } = new List<Visitation>();

    [InverseProperty("user")]
    public virtual ICollection<Visitation> Visitationusers { get; set; } = new List<Visitation>();
}