// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SummerCampManagementSystem.DAL.Models;

public partial class User
{
    public int userId { get; set; }

    public string firstName { get; set; }

    public string lastName { get; set; }

    public string email { get; set; }

    public string phoneNumber { get; set; }

    public string password_hash { get; set; }

    public string role { get; set; }

    public bool isActive { get; set; }

    public DateTime createAt { get; set; }

    public string avatar { get; set; }

    public DateOnly? dob { get; set; }

    public virtual ICollection<Driver> Drivers { get; set; } = new List<Driver>();
}