// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SummerCampManagementSystem.DAL.Models;

public partial class Vehicle
{
    public int vehicleId { get; set; }

    public int vehicleTypeId { get; set; }

    public string vehicleName { get; set; }

    public string vehicleNumber { get; set; }

    public int? capacity { get; set; }

    public string status { get; set; }

    public virtual ICollection<DriverVehicle> DriverVehicles { get; set; } = new List<DriverVehicle>();

    public virtual VehicleType vehicleType { get; set; }
}