// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("VehicleType")]
public partial class VehicleType
{
    [Key]
    public int vehicleTypeId { get; set; }

    [StringLength(255)]
    public string name { get; set; }

    public string description { get; set; }

    public bool? isActive { get; set; }

    [InverseProperty("vehicleTypeNavigation")]
    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}