// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("VehicleSchedule")]
public partial class VehicleSchedule
{
    [Key]
    public int vehicleScheduleId { get; set; }

    public int? vehicleId { get; set; }

    public int? routeId { get; set; }

    public DateOnly? date { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string status { get; set; }

    [ForeignKey("routeId")]
    [InverseProperty("VehicleSchedules")]
    public virtual Route route { get; set; }

    [ForeignKey("vehicleId")]
    [InverseProperty("VehicleSchedules")]
    public virtual Vehicle vehicle { get; set; }
}