// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SummerCampManagementSystem.DAL.Models;

public partial class VehicleType
{
    public int vehicleTypeId { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public bool? isActive { get; set; }

    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}