// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SummerCampManagementSystem.DAL.Models;

[Table("Visitation")]
[Index("approvedBy", Name = "IX_Visitation_approvedBy")]
[Index("camperId", Name = "IX_Visitation_camperId")]
[Index("userId", Name = "IX_Visitation_userId")]
public partial class Visitation
{
    [Key]
    public int visitationId { get; set; }

    public int? userId { get; set; }

    public int? camperId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? visitStartTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? visitEndTime { get; set; }

    public int? approvedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CheckInTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CheckOutTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? updateAt { get; set; }

    [StringLength(50)]
    public string status { get; set; }

    [ForeignKey("approvedBy")]
    [InverseProperty("VisitationapprovedByNavigations")]
    public virtual UserAccount approvedByNavigation { get; set; }

    [ForeignKey("camperId")]
    [InverseProperty("Visitations")]
    public virtual Camper camper { get; set; }

    [ForeignKey("userId")]
    [InverseProperty("Visitationusers")]
    public virtual UserAccount user { get; set; }
}